// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from "../models/drizzle/auth.model";
import * as EnumSchema from "../models/drizzle/enum.model";

const schema = {
	...AuthSchema,
	...EnumSchema
};

export default schema;
